app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
*/
Route::get('/home', function ()  {
    return redirect('/');
});

//Route::get('/', 'HomeController@getIndex');
// Todo esto queda bajo el middleware 'auth'

// Route::get('/', function () {
//     return view('home.index');
    
//     //$personas = \App\Persona::all();
//     //$equipo = \App\Models\Equipo::find(1);
//     //$dispensador = \App\Models\Dispensador::find(1);

//     /*--------------------------------------------------*/
//     if ($elUserSeleccionoConcepto == 'carga') {
//         $origClass = '\App\Models\Dispensador';
//         $destClass = '\App\Models\Equipo';
//     } else {
//         // ...
//     }

//     // ... luego
//     $orig = $origClass::find($idSeleccionadoPorUserDeOrigen);
//     $dest = $destClass::find($idSeleccionadoPorUserDeDestino);
//     /*--------------------------------------------------*/
//     // ---> Todo eso lo puedes meter en un metodo aparte, en el modelo o en la clase que corresponda

//     $charge = new \App\Models\Chargeables();
//     //$charge->destination('dispensador_origen');
//     $charge->concept_id = 1;
//     // desde Chargeable, asigno origen y destino
//     // asi el codigo es mas entendible
//     //$charge->destination()->associate($equipo);
//     $charge->destination()->associate($dispensador); // igual sirve
//     //$charge->origin()->associate($dispensador);
//     $charge->origin()->associate($equipo); // igual sirve
//     // es necesario guardar los cambios
//     $charge->save();

//     //$charge->loaded_origin_id = 1;
//     //$charge->loaded_destination_id = 1;
//     //$charge->loaded_origin_type = 'App\Equipo';
//     //$charge->loaded_destination_type = 'App\Equipo';
//     //dd($charge);

//     //$equipo->chargeables()->save($charge);
//     $dispensador->chargeables('origen')->save($charge);
// });

// Rutas publicas
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group([
    'middleware' => ['auth']
], function() {

    Route::get('select-enterprise', 'Auth\AuthController@enterpriseSelect');
    Route::post('select-enterprise', 'Auth\AuthController@enterpriseSelected');

});

// Este grupo usa un middleware para proteger las rutas para que el usuario inicie sesion antes de acceder
Route::group([
    'middleware' => [
        'auth',
        'force.user.selection'
    ]
], function() {
    Route::get('/', function() {
        return view('home.index');
    });
    
    Route::resource('equipo', 'EquiposController'); //controlador para la adminisración de los equipos (máquinas)
    Route::resource('compra', 'PurchaseController'); //controlador para compra de combustible
    Route::post('compra/{id}/confirm', ['as' => 'compra.confirm', 'uses' => 'PurchaseController@confirm']);
    Route::resource('dispensadores', 'ChargeController'); //controlador para carga de dispensadores
    Route::resource('consumption', 'ConsumptionController'); //controlador para los consumos de los equipos
    Route::resource('loan', 'LoanController'); //controlador para prestamos de combustibles a externos
    Route::resource('loanintern', 'PrestamoInternoController'); //controlador para prestamos de combustibles a internos
    Route::post('loan/return', ['as' => 'loan.return', 'uses' => 'LoanController@return']);
    Route::resource('chargeables', 'ChargeablesController'); //controlador para relaciones polimorficas
    Route::resource('ubicacion', 'UbicacionesController'); //controlador para el mantenedor de ubicaciones (por faenea)
    Route::resource('configuracion', 'ConfiguracionController'); //controlador para el menu de configuración
    Route::resource('newdispensador', 'NewDispensadorController'); //controlador para el ingreso/mantenedor de dispensadores
    Route::resource('initdispensador', 'InitDispensadorController'); //controlador para iniciar saldo de dispensadores por faena
    Route::resource('empresa', 'EmpresasController');
    Route::resource('faena', 'FaenasController');
    Route::resource('catalogo', 'CatalogosController');
    Route::resource('ordentrabajo', 'OrdenTrabajoController');
    Route::resource('persona', 'PersonasController');
    Route::post('ordentrabajo/return', ['as' => 'ordentrabajo.return', 'uses' => 'LoanController@returnOt']);
    
    Route::resource('turnos', 'WorkShiftController');
    Route::get('reportes', 'ReportController@index');
    Route::get('reportes/faena', 'ReportController@operation');
    Route::get('reportes/equipo', 'ReportController@equipment');
    
    // Routes para AJAX
    Route::get('ajax/search-filters/work-shift-by-operation', 'Ajax\SearchFiltersController@workShiftByOperation');
    Route::get('ajax/search-filters/operations-by-enterprise', 'Ajax\SearchFiltersController@operationsByEnterprise');
    Route::get('ajax/search-filters/dispensers-by-enterprise', 'Ajax\SearchFiltersController@dispenserByEnterprise');
    Route::get('ajax/search-filters/equipment-by-enterprise', 'Ajax\SearchFiltersController@equipmentByEnterprise');
    Route::get('ajax/search-filters/types-by-family', 'Ajax\SearchFiltersController@typesByFamily');
    Route::get('ajax/search-filters/models-by-brand', 'Ajax\SearchFiltersController@modelsByBrands');
    Route::get('ajax/search-filters/provider-by-operation', 'Ajax\SearchFiltersController@providerByOperation');
    Route::get('ajax/search-filters/dispenser-by-operation', 'Ajax\SearchFiltersController@dispenserByOperation');
    Route::get('ajax/search-filters/dispenser-by-operation-tct', 'Ajax\SearchFiltersController@dispenserByOperationAddTct');
    Route::get('ajax/search-filters/equipment-by-operation', 'Ajax\SearchFiltersController@equipmentByOperation');
    Route::get('/ajax/search-filters/operators-by-operation', 'Ajax\SearchFiltersController@operatorsByOperation');
    Route::get('/ajax/search-filters/locations-by-operation', 'Ajax\SearchFiltersController@locationsByOperation');
    Route::get('/ajax/search-filters/external-by-operation', 'Ajax\SearchFiltersController@externalByOperation');
    Route::get('/ajax/search-filters/responsible-by-enterprise', 'Ajax\SearchFiltersController@responsibleByEnterprise');
    Route::get('ajax/search-filters/dispenser-by-operation_destination', 'Ajax\SearchFiltersController@dispenserByOperationDestination');
    Route::get('/ajax/search-filters/operations-by-enterprise-for-interloan', 'Ajax\SearchFiltersController@dispenserByOperationForInternLoan');
    
    Route::get('/ajax/search-filters/operations-by-enterprise-loan', 'Ajax\SearchFiltersController@operationsByEnterpriseLoan');
    Route::get('/ajax/search-filters/operations-by-enterprise-for-interloan-destiny', 'Ajax\SearchFiltersController@dispenserByOperationForInternLoanDestiny');
    
    //Route::get('ajax/search-filters/productiveAreas-by-operation', 'Ajax\SearchFiltersController@productiveAreaByOperation');
    
    Route::get('/ajax/search-filters/last-hour-meter-by-equipment', 'Ajax\SearchFiltersController@lastHourMeterByEquipment');
    Route::get('/ajax/load-components/{id}', 'Ajax\SearchFiltersController@componentsByResponsible');
    
    Route::get('ajax/search-filters/affected-by-enterprise', 'Ajax\SearchFiltersController@affectedByEnterprise');
    Route::get('/ajax/search-filters/level_2-by-level_1', 'Ajax\SearchFiltersController@level_2ByLevel_1');
    Route::get('/ajax/search-filters/level_3-by-level_2', 'Ajax\SearchFiltersController@level_3ByLevel_2');
    Route::get('/ajax/search-filters/level_4-by-level_3', 'Ajax\SearchFiltersController@level_4ByLevel_3');
    Route::get('/ajax/search-filters/level_5-by-level_4', 'Ajax\SearchFiltersController@level_5ByLevel_4');
    Route::get('/ajax/search-filters/level_6-by-level_5', 'Ajax\SearchFiltersController@level_6ByLevel_5');
    
    Route::get('/ajax/chargeables/{id}/confirm', 'Ajax\ChargeablesController@confirm');
    Route::get('/ajax/chargeables/fuelreturn', 'Ajax\ChargeablesController@fuelreturn');
});

resources/views/loanintern/create.blade.php
@extends('layout')
@section('content')
<div class="page-header">
    <h1>Préstamo de combustible (faenas Serfocol)</h1>
</div>

<loanformintern inline-template >
    <div class="alert alert-@{{alertType}} alert-dismissible" role="alert" v-show="showAlert" v-html="message"></div>
    {!! Form::open(['v-on'    => 'submit: onSubmit',
                    'route'   => 'loanintern.store', 
                    'class'   => 'form-horizontal' ]) !!}
    
    @include('loanintern.form', ['chargeables' => null])
    
    {!! Form::close() !!}
</loanformintern>
 @endsection

resources/views/loanintern/filters.blade.php
<loaninternfilter inline-template>
    <form action="" class="form-horizontal">
        <fieldset>
            <legend>Filtros de Búsqueda</legend>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{route('loanintern.create')}}">+ Nuevo</a>
            </div>
            <div class="form-group">
                <label for="operation" class="control-label col-md-2">Faena</label>
                <div class="col-xs-2">
                    {!! Form::select('operation', $selectFaenas, null, [
                            'class'          => 'form-control',
                            'placeholder'    => 'Seleccione Faena',
                            'v-model'        => 'operation' ]) !!}
                </div>
                <label for="date" class="control-label col-md-2">Nº Guía</label>
                <div class="col-md-2">
                        {!! Form::text('order_number', null, [
                                'class'      => 'form-control', 
                                'v-model'    => 'order_number' ]) !!}
                </div>
                <!--
                <label for="date" class="control-label col-md-2">Turno</label>
                <div class="col-xs-2">
                    {!! Form::select('work_shift', $selectTurnos, null, [
                            'class'          => 'form-control',
                            'placeholder'    => 'Seleccione Turno',
                            'v-model'        => 'work_shift' ]) !!}
                </div>-->
            </div>
            <div class="form-group">
                <label for="date" class="control-label col-md-2">Empresa destino</label>
                <div class="col-md-2">
                    {!! Form::select('dispenser', $selectEmpresaDestino, null, [
                            'class'        => 'form-control',
                            'placeholder'  => 'Seleccione empresa',
                            'v-model'      => 'dispenser' ]) !!}
                </div>
                <label for="date" class="control-label col-md-2">Faena destino</label>
                <div class="col-md-2">
                    {!! Form::select('external', $selectFaenaDestino, null, [
                            'class'        => 'form-control',
                            'placeholder'  => 'Seleccione faena',
                            'v-model'      => 'external' ]) !!}
                </div>
            </div>
            <div class="form-group">
                <label for="date" class="control-label col-md-2">Fecha desde</label>
                <div class="col-md-2">
                    <div class='input-group date datepicker'>
                        {!! Form::text('date', null, [
                                'class'          => 'form-control datepicker',
                                'v-model'        => 'date_from' ]) !!}
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
                <label for="date" class="control-label col-md-2">Fecha hasta</label>
                <div class="col-md-2">
                    <div class='input-group date datepicker'>
                        {!! Form::text('invoiceDate', null, [
                                'class'         => 'form-control datepicker',
                                'v-model'       => 'date_to' ]) !!}
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                </div>
                
            </div>
            <!--
            <div class="form-group">
                <label for="date" class="control-label col-md-2">Dispensador</label>
                <div class="col-md-2">
                    {!! Form::select('dispenser', $selectDispensadores, null, [
                            'class'        => 'form-control',
                            'placeholder'  => 'Seleccione dispensador',
                            'v-model'      => 'dispenser' ]) !!}
                </div>
            </div>-->
            <div class="form-group">
                <div class="pull-left">
                    <a class="btn btn-primary" href="" data-toggle="modal" data-target="#registroDevolucion">+ Registrar devolución</a>
                </div>
                <div class="pull-right">
                    <a class="btn btn-primary" href="{{route('loan.create')}}">Excel</a>
                    <a class="btn btn-primary" href="#" v-on="click: clearFilters">Limpiar filtros</a>
                    <a class="btn btn-primary" href="#" v-on="click: filterSearch">Buscar</a>
                </div>
            </div>
        </fieldset>
    </form>
        
    <div class="modal fade" role="dialog" aria-labelledby="gridSystemModalLabel" id="registroDevolucion">
        <div class="modal-dialog" role="document">
        {!! Form::open(['route' => 'loan.return', 'class' => 'form-horizontal'])  !!}
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="gridSystemModalLabel">Registro de devoluciones</h4>
                </div>
                <div class="modal-body">
                    <script id="prestamosSeleccionadosTemplate" type="x-tmpl-mustache">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Nº Guía</th>
                                <th>Empresa</th>
                                <th>Litros</th>
                                <th>Fecha</th>
                             </tr>
                        </thead>
                        <tbody>
                            @{{#loans}}
                            <tr>
                                <td width="30">
                                @{{order_number}}
                                    <input type="hidden" name="chargeables[]" value="@{{ id }}" />
                                </td>
                                <td width="45">@{{loaded_destination.name}}</td>
                                <td width="30">@{{liters}}</td>
                                <td width="40">@{{load_date}}</td>
                            </tr>
                            @{{/loans}}
                            <tr>
                                <td width="30" colspan="2">Total</td>
                                <td width="30"><strong>@{{totalLitros}}</strong></td>
                                <td width="40"></td>
                            </tr>
                        </tbody>
                    </table>
                    </script>
                          
                    <div class="prestamosSeleccionados"></div>
                        <div class="form-group">
                            <label class="control-label col-md-2"></label>
                            <div class="col-md-4">
                                <div class="checkbox checkbox-primary">
                                    {!! Form::checkbox('return_type', '1', null, [
                                            'class'        => 'checkbox',
                                            'v-on'         => 'click: isamountStatus' ]) !!}
                                    <label><strong>Registrar devolución en dinero.</strong></label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2">Ingresar monto $</label>
                            <div class="col-md-4">
                                {!! Form::text('amount', Null, [
                                        'class'        => 'form-control',
                                        'v-model'      => 'amount',
                                        'v-attr'       => 'disabled: !isamount' ]) !!}
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <!--<a href="/ajax/chargeables/fuelreturn" class="btn btn-default btn-confirm" >
                        <span class="glyphicon glyphicon-thumbs-up"></span></a>-->
                        <button class="btn btn-primary" type="submit">Guardar</button>
                    </div>
        {!! Form::close() !!}
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
</loaninternfilter>

resources/views/loanintern/form.blade.php
    <!--<div>
        {!! Form::hidden('enterprise_id', current_enterprise()->id, [
                'class'        => 'form-control',
                'v-model'      => 'enterprise' ]) !!}
    </div>-->
    <h3>Antedentes origen del combustible</h3>
    <div class="form-group@{{ errors.init_operation ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Faena origen</label>
        <div class="col-xs-4">
            {!! Form::select('init_operation', $selectFaenas, Null, [
                'class'        => 'form-control',
                'placeholder'  => 'Seleccione faena origen',
                'v-on'         => 'change: operationChangedInternLoan',
                'v-model'      => 'init_operation' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.init_operation" v-text="errors.init_operation"></p>
    </div>
    <div class="form-group@{{ errors.loaded_origin_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Dispensador origen</label>
        <div class="col-xs-4">
            {!! Form::select('loaded_origin_id', [], Null, [
                    'class'        => 'form-control',
                    'placeholder'  => 'Seleccione dispensador origen',
                    'options'      => 'dispenser_interns',
                    'v-model'      => 'dispenser_intern' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.loaded_origin_id" v-text="errors.loaded_origin_id"></p>
    </div>
    <div class="form-group@{{ errors.load_date ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Fecha préstamo</label>
        <div class="col-xs-2">
            {!! Form::date('load_date', Null, ['class' => 'form-control' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.load_date" v-text="errors.load_date"></p>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Turno</label>
        <div class="col-xs-4">
            {!! Form::select('work_shift_id', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione Turno', 
                    'options'      => 'work_shifts', 
                    'v-model'      => 'work_shift' ]) !!}
        </div>
    </div>
    <div class="form-group@{{ errors.order_number ? ' has-error' : '' }}">
        <label class="control-label col-md-2">N° Guía</label>
        <div class="col-xs-2">
            {!! Form::text('order_number', Null, [
                    'class'        => 'form-control',
                    'v-model'      => 'order_number' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.order_number" v-text="errors.order_number"></p>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Ubicación</label>
        <div class="col-xs-2">
            {!! Form::select('ubication_id', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione Ubicación', 
                    'options'      => 'ubications', 
                    'v-model'      => 'ubication' ]) !!}
        </div>
    </div>
    
    <div class="form-group@{{ errors.responsible_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Responsable carga</label>
        <div class="col-xs-4">
            {!! Form::select('responsible_id', $selectResponsables, Null, [
                    'class'        => 'form-control',
                    'placeholder'  => 'Seleccione responsable',
                    'v-model'      => 'responsible' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.responsible_id" v-text="errors.responsible_id"></p>
    </div>
    <div class="form-group@{{ errors.counter ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Contador</label>
        <div class="col-xs-2">
            {!! Form::text('counter', Null, ['class' => 'form-control' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.counter" v-text="errors.counter"></p>
    </div>
    <div class="form-group@{{ errors.liters ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Litros</label>
        <div class="col-xs-2">
            {!! Form::text('liters', Null, ['class' => 'form-control' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.liters" v-text="errors.liters"></p>
    </div>
    <h3>Antedentes destino del combustible</h3>
    <div class="form-group@{{ errors.enterprise_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Empresa destino</label>
        <div class="col-xs-4">
            {!! Form::select('enterprise_id', $selectEmpresas, Null, [
                'class'        => 'form-control',
                'placeholder'  => 'Seleccione empresa destino',
                'v-on'         => 'change: enterpriseChanged',
                'v-model'      => 'enterprise' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.enterprise_id" v-text="errors.enterprise_id"></p>
    </div>
    <div class="form-group@{{ errors.operation_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Faena destino</label>
        <div class="col-xs-4">
            {!! Form::select('operation_id', [], Null, [
                'class'        => 'form-control',
                'placeholder'  => 'Seleccione faena destino',
                'options'      => 'operations',
                'v-model'      => 'operation', 
                'v-on'         => 'change: operationChangedInternLoanDestiny' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.operation_id" v-text="errors.operation_id"></p>
    </div>
    <div class="form-group@{{ errors.loaded_destination_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Dispensador destino</label>
        <div class="col-xs-4">
            {!! Form::select('loaded_destination_id', [], Null, [
                    'class'        => 'form-control',
                    'placeholder'  => 'Seleccione dispensador destino',
                    'options'      => 'dispenser_destinys',
                    'v-model'      => 'dispenser_destiny' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.loaded_destination_id" v-text="errors.loaded_destination_id"></p>
    </div>
    <div class="form-group@{{ errors.operator_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Operador</label>
        <div class="col-xs-4">
            {!! Form::select('operator_id', [], Null, [
                'class'       => 'form-control',
                'placeholder' => 'Seleccione operador',
                'options'     => 'operators',
                'v-model'     => 'operator' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.operator_id" v-text="errors.operator_id"></p>
    </div>
    <div class="form-group">
        <p class="col-md-offset-2 col-md-10">
            <a href="{{ route('loanintern.index') }}" class="btn btn-default">&larr; Cancelar</a>
            <button type="submit" class="btn btn-primary" value="save" name="task">Guardar y salir</button>
        </p>
    </div>

resources/views/loanintern/index.blade.php
@extends('layout')
@section('content')
    
    <h1>Préstamos internos (entre faenas Serfocol)</h1>
    
    @include('loanintern.filters')

    <div id="loaninternfilter"></div>

@endsection