app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
*/
Route::get('/home', function ()  {
    return redirect('/');
});

//Route::get('/', 'HomeController@getIndex');
// Todo esto queda bajo el middleware 'auth'

// Route::get('/', function () {
//     return view('home.index');
    
//     //$personas = \App\Persona::all();
//     //$equipo = \App\Models\Equipo::find(1);
//     //$dispensador = \App\Models\Dispensador::find(1);

//     /*--------------------------------------------------*/
//     if ($elUserSeleccionoConcepto == 'carga') {
//         $origClass = '\App\Models\Dispensador';
//         $destClass = '\App\Models\Equipo';
//     } else {
//         // ...
//     }

//     // ... luego
//     $orig = $origClass::find($idSeleccionadoPorUserDeOrigen);
//     $dest = $destClass::find($idSeleccionadoPorUserDeDestino);
//     /*--------------------------------------------------*/
//     // ---> Todo eso lo puedes meter en un metodo aparte, en el modelo o en la clase que corresponda

//     $charge = new \App\Models\Chargeables();
//     //$charge->destination('dispensador_origen');
//     $charge->concept_id = 1;
//     // desde Chargeable, asigno origen y destino
//     // asi el codigo es mas entendible
//     //$charge->destination()->associate($equipo);
//     $charge->destination()->associate($dispensador); // igual sirve
//     //$charge->origin()->associate($dispensador);
//     $charge->origin()->associate($equipo); // igual sirve
//     // es necesario guardar los cambios
//     $charge->save();

//     //$charge->loaded_origin_id = 1;
//     //$charge->loaded_destination_id = 1;
//     //$charge->loaded_origin_type = 'App\Equipo';
//     //$charge->loaded_destination_type = 'App\Equipo';
//     //dd($charge);

//     //$equipo->chargeables()->save($charge);
//     $dispensador->chargeables('origen')->save($charge);
// });

// Rutas publicas
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group([
    'middleware' => ['auth']
], function() {

    Route::get('select-enterprise', 'Auth\AuthController@enterpriseSelect');
    Route::post('select-enterprise', 'Auth\AuthController@enterpriseSelected');

});

// Este grupo usa un middleware para proteger las rutas para que el usuario inicie sesion antes de acceder
Route::group([
    'middleware' => [
        'auth',
        'force.user.selection'
    ]
], function() {
    Route::get('/', function() {
        return view('home.index');
    });
    
    Route::resource('equipo', 'EquiposController'); //controlador para la adminisración de los equipos (máquinas)
    Route::resource('compra', 'PurchaseController'); //controlador para compra de combustible
    Route::post('compra/{id}/confirm', ['as' => 'compra.confirm', 'uses' => 'PurchaseController@confirm']);
    Route::resource('dispensadores', 'ChargeController'); //controlador para carga de dispensadores
    Route::resource('consumption', 'ConsumptionController'); //controlador para los consumos de los equipos
    Route::resource('loan', 'LoanController'); //controlador para prestamos de combustibles a externos
    Route::resource('loanintern', 'PrestamoInternoController'); //controlador para prestamos de combustibles a internos
    Route::post('loan/return', ['as' => 'loan.return', 'uses' => 'LoanController@return']);
    Route::resource('chargeables', 'ChargeablesController'); //controlador para relaciones polimorficas
    Route::resource('ubicacion', 'UbicacionesController'); //controlador para el mantenedor de ubicaciones (por faenea)
    Route::resource('configuracion', 'ConfiguracionController'); //controlador para el menu de configuración
    Route::resource('newdispensador', 'NewDispensadorController'); //controlador para el ingreso/mantenedor de dispensadores
    Route::resource('initdispensador', 'InitDispensadorController'); //controlador para iniciar saldo de dispensadores por faena
    Route::resource('empresa', 'EmpresasController');
    Route::resource('faena', 'FaenasController');
    Route::resource('catalogo', 'CatalogosController');
    Route::resource('ordentrabajo', 'OrdenTrabajoController');
    Route::resource('persona', 'PersonasController');
    Route::post('ordentrabajo/return', ['as' => 'ordentrabajo.return', 'uses' => 'LoanController@returnOt']);
    
    Route::resource('turnos', 'WorkShiftController');
    Route::get('reportes', 'ReportController@index');
    Route::get('reportes/faena', 'ReportController@operation');
    Route::get('reportes/equipo', 'ReportController@equipment');
    
    // Routes para AJAX
    Route::get('ajax/search-filters/work-shift-by-operation', 'Ajax\SearchFiltersController@workShiftByOperation');
    Route::get('ajax/search-filters/operations-by-enterprise', 'Ajax\SearchFiltersController@operationsByEnterprise');
    Route::get('ajax/search-filters/dispensers-by-enterprise', 'Ajax\SearchFiltersController@dispenserByEnterprise');
    Route::get('ajax/search-filters/equipment-by-enterprise', 'Ajax\SearchFiltersController@equipmentByEnterprise');
    Route::get('ajax/search-filters/types-by-family', 'Ajax\SearchFiltersController@typesByFamily');
    Route::get('ajax/search-filters/models-by-brand', 'Ajax\SearchFiltersController@modelsByBrands');
    Route::get('ajax/search-filters/provider-by-operation', 'Ajax\SearchFiltersController@providerByOperation');
    Route::get('ajax/search-filters/dispenser-by-operation', 'Ajax\SearchFiltersController@dispenserByOperation');
    Route::get('ajax/search-filters/dispenser-by-operation-tct', 'Ajax\SearchFiltersController@dispenserByOperationAddTct');
    Route::get('ajax/search-filters/equipment-by-operation', 'Ajax\SearchFiltersController@equipmentByOperation');
    Route::get('/ajax/search-filters/operators-by-operation', 'Ajax\SearchFiltersController@operatorsByOperation');
    Route::get('/ajax/search-filters/locations-by-operation', 'Ajax\SearchFiltersController@locationsByOperation');
    Route::get('/ajax/search-filters/external-by-operation', 'Ajax\SearchFiltersController@externalByOperation');
    Route::get('/ajax/search-filters/responsible-by-enterprise', 'Ajax\SearchFiltersController@responsibleByEnterprise');
    Route::get('ajax/search-filters/dispenser-by-operation_destination', 'Ajax\SearchFiltersController@dispenserByOperationDestination');
    Route::get('/ajax/search-filters/operations-by-enterprise-for-interloan', 'Ajax\SearchFiltersController@dispenserByOperationForInternLoan');
    
    Route::get('/ajax/search-filters/operations-by-enterprise-loan', 'Ajax\SearchFiltersController@operationsByEnterpriseLoan');
    Route::get('/ajax/search-filters/operations-by-enterprise-for-interloan-destiny', 'Ajax\SearchFiltersController@dispenserByOperationForInternLoanDestiny');
    
    //Route::get('ajax/search-filters/productiveAreas-by-operation', 'Ajax\SearchFiltersController@productiveAreaByOperation');
    
    Route::get('/ajax/search-filters/last-hour-meter-by-equipment', 'Ajax\SearchFiltersController@lastHourMeterByEquipment');
    Route::get('/ajax/load-components/{id}', 'Ajax\SearchFiltersController@componentsByResponsible');
    
    Route::get('ajax/search-filters/affected-by-enterprise', 'Ajax\SearchFiltersController@affectedByEnterprise');
    Route::get('/ajax/search-filters/level_2-by-level_1', 'Ajax\SearchFiltersController@level_2ByLevel_1');
    Route::get('/ajax/search-filters/level_3-by-level_2', 'Ajax\SearchFiltersController@level_3ByLevel_2');
    Route::get('/ajax/search-filters/level_4-by-level_3', 'Ajax\SearchFiltersController@level_4ByLevel_3');
    Route::get('/ajax/search-filters/level_5-by-level_4', 'Ajax\SearchFiltersController@level_5ByLevel_4');
    Route::get('/ajax/search-filters/level_6-by-level_5', 'Ajax\SearchFiltersController@level_6ByLevel_5');
    
    Route::get('/ajax/chargeables/{id}/confirm', 'Ajax\ChargeablesController@confirm');
    Route::get('/ajax/chargeables/fuelreturn', 'Ajax\ChargeablesController@fuelreturn');
});

app/Models/OrdenTrabajo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\OrdenTrabajo
 *
 * @mixin \Eloquent
 */
class OrdenTrabajo extends Model
{
    protected $table = "work_order";
	
	protected $primaryKey = 'id';
}

app/Http/Controllers/OrdenTrabajoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class OrdenTrabajoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        $selectFaenas       = \App\Models\Faena::where('enterprise_id', '=', current_enterprise()->id)
                                    ->where('external', '<>', 1)
                                    ->where('visible', '=', 1)
                                    ->lists('name', 'id');
                                 
        $selectConceptos    = \App\Models\Concepto::where('id', '=', 3)->first();
        
        
        $selectAfectado     = \App\Models\Empresa::find(current_enterprise()->id)
                                    //where('id', '=', )
                                    ->afectado()
                                    ->get([\DB::raw("CONCAT(`primary_last_name`,' ',`second_last_name`,', ',`person`.`name`) as fullName"), 'person.id'])
                                    ->lists('fullName', 'id');
        
        
        $selectResponsible  = \App\Models\Empresa::find(current_enterprise()->id)
                                    ->operator()
                                    ->where('its_responsible', '=', 1)
                                    ->where ('active', '=', 1)
                                    ->orderBy('primary_last_name', 'ASC')
                                    ->get([\DB::raw("CONCAT(`primary_last_name`,' ',`second_last_name`,', ',`name`) as fullName"), 'person.id'])
                                    //->get([\DB::raw("CONCAT(`name`,' ',`primary_last_name`,' ',`second_last_name`) as fullName"), 'person.id'])
                                    ->lists('fullName', 'id');
                                    
        $selectNivel1       = \App\Models\TipoSolicitud::all()
                                    ->lists('name', 'id');
                            
        return view('ordentrabajo.create')->with([
            //'selectEmpresas'        => $selectEmpresas
            'selectFaenas'          => $selectFaenas,
            'selectAfectado'        => $selectAfectado,
            "selectResponsible"     => $selectResponsible,            
            'selectConceptos'       => $selectConceptos,
            'selectNivel1'          => $selectNivel1
        ]);
    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        //
    }
    
    public function returnOt(Request $request){
        $componentes = \App\Models\Componente::where('responsible_id', '=', 190)->get();
        
        return $componentes;
    }
}

resources/views/ordentrabajo/create.blade.php
@extends('layout')
 @section('content')
<div class="page-header">
    <h1>Orden de trabajo</h1>
</div>
<otform inline-template >
    <div class="alert alert-@{{alertType}} alert-dismissible" role="alert" v-show="showAlert" v-html="message"></div>
{!! Form::open(['v-on' => 'submit: onSubmit' ,'route' => 'ordentrabajo.store', 'class' => 'form-horizontal']) !!}
    
    @include('ordentrabajo.form')
    
{!! Form::close() !!}
</otform>
@endsection

resources/views/ordentrabajo/form.blade.php
    <div>
        {!! Form::hidden('enterprise_id', current_enterprise()->id) !!}
    </div>
    <div class="form-group@{{ errors.operation_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Faena</label>
        <div class="col-md-4">
            {!! Form::select('operation_id', $selectFaenas, Null, [
                    'class'        => 'form-control',
                    'placeholder'  => 'Seleccione Faena',
                    'v-on'         => 'change: operationChanged',
                    'v-model'      => 'operation' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.operation_id" v-text="errors.operation_id"></p>
    </div>
    <div>
        {!! Form::hidden('concept_id', $selectConceptos->id, []) !!}
    </div>
    <div class="form-group@{{ errors.attention_date ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Fecha atención</label>
        <div class="col-md-2">
            {!! Form::date('attention_date', Null, ['class'=>'form-control']) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.attention_date" v-text="errors.attention_date"></p>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Usuario afectado</label>
        <div class="col-md-4">
            {!! Form::select('affected_id', $selectAfectado, Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione usuario', 
                    
                    'v-model'      => 'affected' ]) !!}
        </div>
        <a class="glyphicon glyphicon-tags" href="#" data-toggle="modal" data-target="#seleccionComponentes"></a>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Descripción</label>
        <div class="col-md-4">
            {!! Form::textarea('description', Null, [
                    'class'        => 'form-control' ]) !!}
        </div>
        <!--<p class="help-block col-md-10 col-md-offset-2" v-show="errors.affected_id" v-text="errors.affected_id"></p>-->
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Actividad</label>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Tipo solicitud</label>
        <div class="col-md-4">
            {!! Form::select('type_request_id', $selectNivel1, Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione tipo de solicitud',
                    'v-on'         => 'change: requestChange',
                    'v-model'      => 'level_1' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Plataforma</label>
        <div class="col-md-4">
            {!! Form::select('platform_id', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione plataforma',
                    'v-on'         => 'change: platformChange',
                    'v-model'      => 'level_2',
                    'options'      => 'level_2s' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Sistema</label>
        <div class="col-md-4">
            {!! Form::select('n3_system_id', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione sistema',
                    'v-on'         => 'change: systemChange',
                    'v-model'      => 'level_3',
                    'options'      => 'level_3s' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Sub-sistema</label>
        <div class="col-md-4">
            {!! Form::select('n4_sub_system_id', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione sub-sistema',
                    'v-on'         => 'change: subSystemChange',
                    'v-model'      => 'level_4',
                    'options'      => 'level_4s' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Nivel 5</label>
        <div class="col-md-4">
            {!! Form::select('n5', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione nivel 5',
                    'v-on'         => 'change: n5Change',
                    'v-model'      => 'level_5',
                    'options'      => 'level_5s' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Nivel 6</label>
        <div class="col-md-4">
            {!! Form::select('n6', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione nivel 6',
                    'v-model'      => 'level_6',
                    'options'      => 'level_6s' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <p class="col-md-offset-2 col-md-10">
            <a href="{{ route('ordentrabajo.index') }}" class="btn btn-default">&larr; Cancelar</a>
            <button type="submit" class="btn btn-primary" value="save" name="task">Guardar y salir</button>
            <button type="submit" class="btn btn-primary" value="save_n_new" name="task">Guardar y continuar</button>
        </p>
    </div>
    
    
    <div class="modal fade" role="dialog" aria-labelledby="gridSystemModalLabel" id="seleccionComponentes">
        <div class="modal-dialog" role="document">
        {!! Form::open(['route' => 'ordentrabajo.return', 'class' => 'form-horizontal'])  !!}
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="gridSystemModalLabel">Componentes asociados por usuario</h4>
                </div>
                <div class="modal-body">
                    
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Patente</th>
                                <th>Nombre</th>
                                <th>Marca</th>
                                <th>Modelo</th>
                                <th>N° de serie</th>
                                <th>Familia</th>
                             </tr>
                        </thead>
                        <tbody>
                            
                            <tr v-repeat="componentes">
                                <td width="45" v-text="component | equipmentPatent component_type"></td>
                                <td width="30" v-text="component | equipmentName component_type"></td>
                                <td width="45" v-text="component | equipmentBrand component_type"></td>
                                <td width="30" v-text="component | equipmentModel component_type"></td>
                                <td width="40" v-text="component | equipmentSerial component_type"></td>
                                <td width="40" v-text="component | equipmentFamily component_type"></td>
                            </tr>
                        </tbody>
                    </table>
                    
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <!--<a href="/ajax/chargeables/fuelreturn" class="btn btn-default btn-confirm" >
                        <span class="glyphicon glyphicon-thumbs-up"></span></a>-->
                        <button class="btn btn-primary" type="submit">Guardar</button>
                    </div>
        {!! Form::close() !!}
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

resources/views/ordentrabajo/index.blade.php
@extends('layout')
@section('content')
    
    <h1>Orden de Trabajo</h1>
    
    @include('ordentrabajo.filters')
    
    <div id="otfilter"></div>

@endsection