app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
*/
Route::get('/home', function ()  {
    return redirect('/');
});

//Route::get('/', 'HomeController@getIndex');
// Todo esto queda bajo el middleware 'auth'

// Route::get('/', function () {
//     return view('home.index');
    
//     //$personas = \App\Persona::all();
//     //$equipo = \App\Models\Equipo::find(1);
//     //$dispensador = \App\Models\Dispensador::find(1);

//     /*--------------------------------------------------*/
//     if ($elUserSeleccionoConcepto == 'carga') {
//         $origClass = '\App\Models\Dispensador';
//         $destClass = '\App\Models\Equipo';
//     } else {
//         // ...
//     }

//     // ... luego
//     $orig = $origClass::find($idSeleccionadoPorUserDeOrigen);
//     $dest = $destClass::find($idSeleccionadoPorUserDeDestino);
//     /*--------------------------------------------------*/
//     // ---> Todo eso lo puedes meter en un metodo aparte, en el modelo o en la clase que corresponda

//     $charge = new \App\Models\Chargeables();
//     //$charge->destination('dispensador_origen');
//     $charge->concept_id = 1;
//     // desde Chargeable, asigno origen y destino
//     // asi el codigo es mas entendible
//     //$charge->destination()->associate($equipo);
//     $charge->destination()->associate($dispensador); // igual sirve
//     //$charge->origin()->associate($dispensador);
//     $charge->origin()->associate($equipo); // igual sirve
//     // es necesario guardar los cambios
//     $charge->save();

//     //$charge->loaded_origin_id = 1;
//     //$charge->loaded_destination_id = 1;
//     //$charge->loaded_origin_type = 'App\Equipo';
//     //$charge->loaded_destination_type = 'App\Equipo';
//     //dd($charge);

//     //$equipo->chargeables()->save($charge);
//     $dispensador->chargeables('origen')->save($charge);
// });

// Rutas publicas
// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');
// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group([
    'middleware' => ['auth']
], function() {

    Route::get('select-enterprise', 'Auth\AuthController@enterpriseSelect');
    Route::post('select-enterprise', 'Auth\AuthController@enterpriseSelected');

});

// Este grupo usa un middleware para proteger las rutas para que el usuario inicie sesion antes de acceder
Route::group([
    'middleware' => [
        'auth',
        'force.user.selection'
    ]
], function() {
    Route::get('/', function() {
        return view('home.index');
    });
    
    Route::resource('equipo', 'EquiposController'); //controlador para la adminisración de los equipos (máquinas)
    Route::resource('compra', 'PurchaseController'); //controlador para compra de combustible
    Route::post('compra/{id}/confirm', ['as' => 'compra.confirm', 'uses' => 'PurchaseController@confirm']);
    Route::resource('dispensadores', 'ChargeController'); //controlador para carga de dispensadores
    Route::resource('consumption', 'ConsumptionController'); //controlador para los consumos de los equipos
    Route::resource('loan', 'LoanController'); //controlador para prestamos de combustibles a externos
    Route::resource('loanintern', 'PrestamoInternoController'); //controlador para prestamos de combustibles a internos
    Route::post('loan/return', ['as' => 'loan.return', 'uses' => 'LoanController@return']);
    Route::resource('chargeables', 'ChargeablesController'); //controlador para relaciones polimorficas
    Route::resource('ubicacion', 'UbicacionesController'); //controlador para el mantenedor de ubicaciones (por faenea)
    Route::resource('configuracion', 'ConfiguracionController'); //controlador para el menu de configuración
    Route::resource('newdispensador', 'NewDispensadorController'); //controlador para el ingreso/mantenedor de dispensadores
    Route::resource('initdispensador', 'InitDispensadorController'); //controlador para iniciar saldo de dispensadores por faena
    Route::resource('empresa', 'EmpresasController');
    Route::resource('faena', 'FaenasController');
    Route::resource('catalogo', 'CatalogosController');
    Route::resource('ordentrabajo', 'OrdenTrabajoController');
    Route::resource('persona', 'PersonasController');
    Route::post('ordentrabajo/return', ['as' => 'ordentrabajo.return', 'uses' => 'LoanController@returnOt']);
    
    Route::resource('turnos', 'WorkShiftController');
    Route::get('reportes', 'ReportController@index');
    Route::get('reportes/faena', 'ReportController@operation');
    Route::get('reportes/equipo', 'ReportController@equipment');
    
    // Routes para AJAX
    Route::get('ajax/search-filters/work-shift-by-operation', 'Ajax\SearchFiltersController@workShiftByOperation');
    Route::get('ajax/search-filters/operations-by-enterprise', 'Ajax\SearchFiltersController@operationsByEnterprise');
    Route::get('ajax/search-filters/dispensers-by-enterprise', 'Ajax\SearchFiltersController@dispenserByEnterprise');
    Route::get('ajax/search-filters/equipment-by-enterprise', 'Ajax\SearchFiltersController@equipmentByEnterprise');
    Route::get('ajax/search-filters/types-by-family', 'Ajax\SearchFiltersController@typesByFamily');
    Route::get('ajax/search-filters/models-by-brand', 'Ajax\SearchFiltersController@modelsByBrands');
    Route::get('ajax/search-filters/provider-by-operation', 'Ajax\SearchFiltersController@providerByOperation');
    Route::get('ajax/search-filters/dispenser-by-operation', 'Ajax\SearchFiltersController@dispenserByOperation');
    Route::get('ajax/search-filters/dispenser-by-operation-tct', 'Ajax\SearchFiltersController@dispenserByOperationAddTct');
    Route::get('ajax/search-filters/equipment-by-operation', 'Ajax\SearchFiltersController@equipmentByOperation');
    Route::get('/ajax/search-filters/operators-by-operation', 'Ajax\SearchFiltersController@operatorsByOperation');
    Route::get('/ajax/search-filters/locations-by-operation', 'Ajax\SearchFiltersController@locationsByOperation');
    Route::get('/ajax/search-filters/external-by-operation', 'Ajax\SearchFiltersController@externalByOperation');
    Route::get('/ajax/search-filters/responsible-by-enterprise', 'Ajax\SearchFiltersController@responsibleByEnterprise');
    Route::get('ajax/search-filters/dispenser-by-operation_destination', 'Ajax\SearchFiltersController@dispenserByOperationDestination');
    Route::get('/ajax/search-filters/operations-by-enterprise-for-interloan', 'Ajax\SearchFiltersController@dispenserByOperationForInternLoan');
    
    Route::get('/ajax/search-filters/operations-by-enterprise-loan', 'Ajax\SearchFiltersController@operationsByEnterpriseLoan');
    Route::get('/ajax/search-filters/operations-by-enterprise-for-interloan-destiny', 'Ajax\SearchFiltersController@dispenserByOperationForInternLoanDestiny');
    
    //Route::get('ajax/search-filters/productiveAreas-by-operation', 'Ajax\SearchFiltersController@productiveAreaByOperation');
    
    Route::get('/ajax/search-filters/last-hour-meter-by-equipment', 'Ajax\SearchFiltersController@lastHourMeterByEquipment');
    Route::get('/ajax/load-components/{id}', 'Ajax\SearchFiltersController@componentsByResponsible');
    
    Route::get('ajax/search-filters/affected-by-enterprise', 'Ajax\SearchFiltersController@affectedByEnterprise');
    Route::get('/ajax/search-filters/level_2-by-level_1', 'Ajax\SearchFiltersController@level_2ByLevel_1');
    Route::get('/ajax/search-filters/level_3-by-level_2', 'Ajax\SearchFiltersController@level_3ByLevel_2');
    Route::get('/ajax/search-filters/level_4-by-level_3', 'Ajax\SearchFiltersController@level_4ByLevel_3');
    Route::get('/ajax/search-filters/level_5-by-level_4', 'Ajax\SearchFiltersController@level_5ByLevel_4');
    Route::get('/ajax/search-filters/level_6-by-level_5', 'Ajax\SearchFiltersController@level_6ByLevel_5');
    
    Route::get('/ajax/chargeables/{id}/confirm', 'Ajax\ChargeablesController@confirm');
    Route::get('/ajax/chargeables/fuelreturn', 'Ajax\ChargeablesController@fuelreturn');
});

app/Models/Equipo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Equipo
 *
 * @property-read \App\Models\Empresa $enterprise
 * @property-read \App\Models\Faena $operation
 * @property-read \App\Models\Familia $category
 * @property-read \App\Models\Tipo $type
 * @property-read \App\Models\Marca $brand
 * @property-read \App\Models\Modelo $model
 * @property-read \App\Models\Status $status
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Chargeable[] $charger
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Chargeable[] $loaded
 * @mixin \Eloquent
 * @property integer $id
 * @property integer $enterprise_id
 * @property integer $operation_id
 * @property integer $category_id
 * @property integer $type_id
 * @property integer $brand_id
 * @property integer $model_id
 * @property integer $owner_id
 * @property integer $status_id
 * @property integer $type_identification_id
 * @property integer $fuel_tank_capacity
 * @property string $cc
 * @property string $patent
 * @property string $serial_number
 * @property string $engine
 * @property integer $year
 * @property integer $lease
 * @property integer $active
 * @property integer $fuel
 * @property integer $dispenser
 * @property integer $created_by
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereEnterpriseId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereOperationId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereCategoryId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereTypeId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereBrandId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereModelId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereOwnerId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereStatusId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereTypeIdentificationId($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereFuelTankCapacity($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereCc($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo wherePatent($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereSerialNumber($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereEngine($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereYear($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereLease($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereActive($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereFuel($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereDispenser($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereCreatedBy($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereCreatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Equipo whereUpdatedAt($value)
 */
class Equipo extends Model implements CanBeAChargeInterface
{
    use CanBeAChargeTrait;

    //
    protected $table = 'equipment';

    protected $primaryKey = 'id';
    
    protected $with = ['brand', 'model', 'category'];

    public function enterprise(){
        return $this->belongsTo('App\Models\Empresa', 'enterprise_id');
    }

    public function operation(){
        return $this->belongsTo('App\Models\Faena', 'operation_id');
    }

    public function category(){
        return $this->belongsTo('App\Models\Familia', 'category_id');
    }

    public function type(){
        return $this->belongsTo('App\Models\Tipo', 'type_id');
    }

    public function brand(){
        return $this->belongsTo('App\Models\Marca', 'brand_id');
    }

    public function model()
    {
        return $this->belongsTo('App\Models\Modelo', 'model_id');
    }
    
    public function status(){
        return $this->belongsTo('App\Models\Status', 'status_id');
    }
    /*
    public function component()
    {
        return $this->morphMany('App\Models\Componente', 'equipment');
    }*/
    public function component()
    {
        return $this->morpTohMany('App\Models\Componente', 'component');
    }
    
    public $timestamps = true;
	
	protected $dates = [
	    'created_at'
	];
	
	protected $fillable = [
		'enterprise_id',
        'operation_id',
		'cc',
		'patent',
		'type_identification_id',
		'category_id',
		'type_id',
		'brand_id',
		'model_id',
		'serial_number',
		'engine',
		'year',
		'lease',
		'owner_id',
		'active',
		'status_id',
		'fuel',
		'dispenser',
		'fuel_tank_capacity'
	];
}

resources/views/equipos/create.blade.php
@extends('layout')
@section('content')
<div class="page-header">
    <h1>Ingreso de equipo</small></h1>
</div>

<equipmentform inline-template>
    <div class="alert alert-@{{alertType}} alert-dismissible" role="alert" v-show="showAlert" v-html="message"></div>
        {!! Form::open(['v-on' => 'submit: onSubmit' ,'route' => 'equipo.store', 'class' => 'form-horizontal']) !!}
            @include('equipos.form')
        {!! Form::close() !!}
</equipmentform>
@endsection

resources/views/equipos/edit.blade.php
@extends('layout')
@section('content')

<div class="page-header">
    <h1>Ingreso de equipo <small>Editar</small></h1>
</div>

<equipmentform inline-template edit="{{ route('equipo.edit', ['equipos' => $equipos->id]) }}">
    {!! Form::model($equipos, [
        'v-on'    => 'submit: onSubmit',
        'route'   => ['equipo.update', 'equipos' => $equipos->id],
        'class'   => 'form-horizontal',
        'method'  => 'PUT' ]) !!}
        
        @include('equipos.form')
        
    {!! Form::close() !!}
</equipmentform>
@endsection

resources/views/equipos/filters.blade.php
    <equipmentfilters inline-template data-url="{{ route('equipo.index') }}">
        <form action="" class="form-horizontal">
        <fieldset>
            <legend>Filtros de Búsqueda</legend>
            
            <div class="pull-right">
                <a class="btn btn-primary" href="{{route('equipo.create')}}">+ Nuevo</a>
            </div>
            
            <div class="form-group">
                <label class="control-label col-md-2">Empresa</label>
                <div class="col-xs-2">
                    {!! Form::select('enterprise_id', $selectEmpresas, Null, [
                        'class'        =>'form-control',
                        'placeholder'  => 'Seleccione Empresa',
                        'v-on'         => 'change: enterpriseChanged',
                        'v-model'      => 'enterprise']) !!}
                </div>
                <label class="control-label col-md-2">Faena</label>
                <div class="col-xs-2">
                    {!! Form::select('operation_id', $selectFaenas, Null, [
                        'class'        => 'form-control',
                        'placeholder'  => 'Seleccione Faena',
                        'v-model'      => 'operation' ]) !!}
                </div>
                <div class="col-md-2">
                    <div class="checkbox checkbox-primary">
                        {!! Form::checkbox('active', null, null, [
                            'class'          => 'checkbox', 
                            'v-model'        => 'active' ]) !!}
                            <label><strong>Equipos inactivos</strong></label>
                    </div>
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-md-2">Centro de costo</label>
                <div class="col-md-2">
                    {!! Form::text('cc', null, [
                        'class'        => 'form-control', 
                        'v-model'      => 'cc' ]) !!}
                </div>
                <label class="control-label col-md-2">Equipo</label>
                <div class="col-md-2">
                    {!! Form::select('equipment', $selectEquipos, null, [
                        'class'          => 'form-control',
                        'placeholder'    => 'Seleccione Equipo', 
                        'v-model'        => 'equipment' ]) !!}
                </div>
                <label class="control-label col-md-2" width="150">Patente</label>
                <div class="col-md-2">
                    {!! Form::text('patent', null, [
                        'class'        => 'form-control', 
                        'v-model'      => 'patent' ]) !!}
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-md-2">Familia</label>
                <div class="col-xs-2">
                    {!! Form::select('category_id', $selectFamilias, Null, [
                        'class'       =>'form-control',
                        'placeholder' => 'Seleccione Familia',
                        'v-model'     => 'category' ]) !!}
                </div>
                <label class="control-label col-md-2">Tipo</label>
                <div class="col-xs-2">
                    {!! Form::select('type_id', $selectTipos, Null, [
                        'class'        => 'form-control',
                        'placeholder'  => 'Seleccione Tipo',
                        'v-model'      => 'type']) !!}
                </div>
                <label class="control-label col-md-2">Condición</label>
                <div class="col-xs-2">
                    {!! Form::select('status_id', $selectStatus, Null, [
                        'class'        => 'form-control',
                        'placeholder'  => 'Seleccione condición',
                        'v-model'      => 'condition']) !!}
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Marca</label>
                <div class="col-xs-2">
                    {!! Form::select('brand_id', $selectMarcas, Null, [
                        'class'       => 'form-control',
                        'placeholder' => 'Seleccione marca',
                        'v-on'        => 'change: brandChanged',
                        'v-model'     => 'brand' ]) !!}
                </div>
                <label class="control-label col-md-2">Modelo</label>
                <div class="col-xs-2">
                    {!! Form::select('model_id', [], Null, [
                        'class'        => 'form-control',
                        'placeholder'  => 'Seleccione modelo',
                        'v-model'      => 'model',
                        'options'      => 'models' ]) !!}
                </div>
                <div class="col-md-2">
                    <div class="checkbox checkbox-primary">
                        {!! Form::checkbox('lease', 1, false, [
                            'class'          => 'checkbox',
                            'v-model'        => 'lease' ]) !!}
                            <label><strong>Arriendo</strong></label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="pull-right">
                    <a class="btn btn-primary" href="#" v-on="click: export">Excel</a>
                    <a class="btn btn-primary" href="#" v-on="click: clearFilters">Limpiar filtros</a>
                    <a class="btn btn-primary" href="#" v-on="click: filterSearch">Buscar</a>
                </div>
            </div>
        </fieldset>
        </form>
    </equipmentfilters>
            

resources/views/equipos/form.blade.php
    <div class="form-group@{{ errors.enterprise_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Empresa</label>
        <div class="col-xs-4">
            {!! Form::select('enterprise_id', $selectEmpresas, Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione empresa',
                    'v-on'         => 'change: enterpriseChanged',
                    'v-model'      => 'enterprise' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.enterprise_id" v-text="errors.enterprise_id"></p>
    </div>
    <div class="form-group@{{ errors.operation_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Faena</label>
        <div class="col-xs-4">
            {!! Form::select('operation_id', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione faena',
                    'options'      => 'operations', 
                    'v-model'      => 'operation']) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.operation_id" v-text="errors.operation_id"></p>
    </div>
    <div class="form-group@{{ errors.cc ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Centro de Costo</label>
        <div class="col-xs-2">
            {!! Form::text('cc', Null, [
                    'class'    => 'form-control']) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.cc" v-text="errors.cc"></p>
    </div>
    <div class="form-group@{{ errors.patent ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Patente</label>
        <div class="col-xs-2">
            {!! Form::text('patent', Null, [
                    'class'    => 'form-control']) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.patent" v-text="errors.patent"></p>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Tipo Identificación</label>
        <div class="col-xs-4">
            {!! Form::select('type_identification_id', $selectTipoIdentif, Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione Tipo Identificación',
                    'v-model'      => 'typeidentification' ]) !!}
        </div>
    </div>
    <div class="form-group@{{ errors.category_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Familia</label>
        <div class="col-xs-2">
            {!! Form::select('category_id', $selectFamilias, Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione Familia', 
                    'v-on'         => 'change: actualizaTipos', 
                    'v-model'      => 'category']) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.category_id" v-text="errors.category_id"></p>
    </div>
    <div class="form-group@{{ errors.type_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Tipo</label>
        <div class="col-md-2">
            {!! Form::select('type_id', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione Tipo', 
                    'options'      => 'types',
                    'v-model'      => 'type']) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.type_id" v-text="errors.type_id"></p>
    </div>
    <div class="form-group@{{ errors.brand_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Marca</label>
        <div class="col-xs-2">
            {!! Form::select('brand_id', $selectMarcas, Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione Marca', 
                    'v-on'         => 'change: actualizaModelos', 
                    'v-model'      => 'brand']) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.brand_id" v-text="errors.brand_id"></p>
    </div>
    <div class="form-group@{{ errors.model_id ? ' has-error' : '' }}">
        <label class="control-label col-md-2">Modelo</label>
        <div class="col-xs-2">
            {!! Form::select('model_id', [], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione Modelo', 
                    'options'      => 'models', 
                    'v-model'      => 'model' ]) !!}
        </div>
        <p class="help-block col-md-10 col-md-offset-2" v-show="errors.model_id" v-text="errors.model_id"></p>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Serie motor</label>
        <div class="col-xs-2">
            {!! Form::text('serial_number', Null, [
                    'class'    => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Serie chasis</label>
        <div class="col-xs-2">
            {!! Form::text('engine', Null, [
                    'class'    => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Año</label>
        <div class="col-xs-2">
            {!! Form::selectYear('year', '1960', '2050', '2015', [
                    'class'    => 'form-control']) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2"></label>
        <div class="col-md-6">
            <div class="checkbox checkbox-primary">
                {!! Form::hidden('lease', 0, null) !!}
                {!! Form::checkbox('lease', 1, null, [
                        'class'    => 'form-control']) !!}
                <label><strong>¿Es arrendado?</strong></label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Propietario</label>
        <div class="col-xs-4">
            {!! Form::select('owner_id', $selectPropietario, Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione propietario',
                    'v-model'      => 'owner' ]) !!}
        </div>
    </div>
     <div class="form-group">
        <label class="control-label col-md-2">Estatus</label>
        <div class="col-xs-2">
            {!! Form::select('active', ['1' => 'Activo', '0' => 'Inactivo'], Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione estatus' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Condición</label>
        <div class="col-xs-2">
            {!! Form::select('status_id', $selectStatus, Null, [
                    'class'        => 'form-control', 
                    'placeholder'  => 'Seleccione condición' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Combustible</label>
        <div class="col-xs-4">
            {!! Form::select('fuel', config('serfocol.form.combustiblesSelect'), null, [
                    'class'        => 'form-control',
                    'placeholder'  => 'Seleccione combustible utilizado' ]) !!}
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2"></label>
        <div class="col-md-2">
            <div class="checkbox checkbox-primary">
                {!! Form::hidden('dispenser', 0, null) !!}
                {!! Form::checkbox('dispenser', 1, null, [
                        'class'    => 'form-control']) !!}
                <label><strong>¿El equipo, es dispensador de combustible?</strong></label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-2">Capacidad estanque (lts.)</label>
        <div class="col-xs-2">
            {!! Form::text('fuel_tank_capacity', Null, [
                    'class'    => 'form-control']) !!}
        </div>
    </div>
    
    <div class="form-group">
        <p class="col-md-offset-2 col-md-10">
            <a class="btn btn-default" href="{{ route('equipo.index') }}" >&larr; Cancelar</a>
            <button type="submit" class="btn btn-primary" value="save" name="task">Guardar y salir</button>
            <!--
            <button type="submit" class="btn btn-primary" value="save_n_new" name="task">Guardar y continuar</button>
            -->
        </p>
    </div>

resources/views/equipos/index.blade.php
@extends('layout')
@section('content')

    <h1>Listado de equipos Serfocol</h1>
    
    @include('equipos.filters')
    
    <div id="equipmentFilters"></div>
    
@endsection